### ISSUE TITLE
cmd + alt + up + up doesn't work anymore

### ISSUE THREAD

**Issue by runakash** [jackdoe/butter#4]
cmd + alt + up + up to move the window to the full screen doesn't work anymore.

macOS High Sierra
Version 10.13.4

**Comment by jackdoe** [comment]
i have been delaying updating to high sierra, so i have no way to test
are the other shortcuts working?

**Comment by akashr** [comment]
Ohh, I tried for few other applications, apparently the full screen doesn't work for 'Franz', but seems to work fine for the sublime. Rest of the shortcuts works pretty well. Maybe Franz is overriding that shortcut. False alarm, I think you can delete this issue.
